### ISSUE TITLE
Add support for Add/Remove Device to/from Collection Endpoints

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-c#13]
Add support for the following endpoints that were added to the [Collections API](https://m2x.att.com/developer/documentation/v2/collections):
* [Add Device to Collection](https://m2x.att.com/developer/documentation/v2/collections#Add-device-to-collection)
* [Remove Device from Collection](https://m2x.att.com/developer/documentation/v2/collections#Remove-device-from-collection)

**Comment by kristinpeterson** [comment]
@xxuejie thank you for implementing! 

Reference: https://github.com/attm2x/m2x-c/releases/tag/3.1.2

**Comment by kristinpeterson** [comment]
Yikes! I didn't see this PR: https://github.com/attm2x/m2x-c/pull/14

Thank you @Hamdih4 for implementing!

**Comment by xxuejie** [comment]
@kristinpeterson All the credit for this goes to @Hamdih4! I just hit a button :)
