### ISSUE TITLE
Add Post Device Update (Single Values to Multiple Streams)

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-c#7]
Add [Post Device Update (Single Values to Multiple Streams)](https://m2x.att.com/developer/documentation/v2/device#Post-Device-Update--Single-Values-to-Multiple-Streams-) endpoint to the following client libraries, method should be named `postDeviceUpdate`

**Comment by xxuejie** [comment]
We do have this API implemented at [here](https://github.com/attm2x/m2x-c/blob/master/device.h#L46), just a slight different naming is used.

**Comment by fsaravia** [comment]
@xxuejie note that those are two different APIs, one is Post Device Updates and the new one is Post Device Update, they work slightly different in the sense that the later allows user to omit the timestamp and use the one of the M2X server.

**Comment by xxuejie** [comment]
@fsaravia Ahhh, I see, thanks for clarifying this, I will add this new API!

**Comment by xxuejie** [comment]
Solved by https://github.com/attm2x/m2x-c/commit/2b64e4eedc3cb6c8cff236a5b4d0b54307c867ff

**Comment by fsaravia** [comment]
Thanks!

**Comment by kristinpeterson** [comment]
:star2:
