### ISSUE TITLE
Add Support for Commands API

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-c#9]
Add support for the [Commands API](https://m2x.att.com/developer/documentation/v2/commands).

**Comment by kristinpeterson** [comment]
As mentioned here: https://github.com/attm2x/m2x-nanode/issues/4#issuecomment-185326735

I think we should add support for the [process](https://m2x.att.com/developer/documentation/v2/commands#Device-Marks-a-Command-as-Processed) & [reject](https://m2x.att.com/developer/documentation/v2/commands#Device-Marks-a-Command-as-Rejected) Command endpoints.

**Comment by xxuejie** [comment]
Actually these are 2 different libraries: this C library is more complete and can implement everything including Collection API, Metadata API, Job API and Command API. In fact I've already got command API implemented at here: https://github.com/attm2x/m2x-c/blob/master/command.h

**Comment by kristinpeterson** [comment]
@xxuejie ah, thank you!
